### ISSUE TITLE
Transform messes with privileges?

### ISSUE THREAD

**Issue by murphyke** [PEDSnet/pedsnetdcc#80] opened 2016-09-22 14:02 UTC
Ritu reports that she can't access `stlouis_pedsnet`.  I will fix it manually in this case.

**Comment by murphyke** [comment] 2016-09-22 15:16
Possibilities: 1) the default privileges were not applied because the "wrong" user was used to execute the table creation statements, or 2) the schema was recreated (without default privileges being applied to it).

**Comment by aaron0browne** [comment] 2016-09-22 17:25
I think the problem is that it's actually a different schema. It started as the `stlouis_pedsnet_transformed` schema and then was renamed to `stlouis_pedsnet`. So we just need to make sure that when that schema is created it gets the same treatment as the original `stlouis_pedsnet` schema, which has been renamed to `stlouis_pedsnet_backup`.

**Comment by eceowl** [comment] 2017-05-02 17:25
fixed in #89

**Closed by eceowl** 2017-05-02 17:25 UTC
